using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
namespace Euler_2
{
    class Program
    {
        // using memoization technique
        static IDictionary<int, int> cache = new Dictionary<int, int>();

        static void Main(string[] args)
        {
            int result = 0;
            int i = 1;
            int fibNumber = 0;
            while (fibNumber < 4000000)
            {
                fibNumber = fibonacci(i);
                    if (fibNumber % 2 == 0)
                    {
                        result += fibNumber;
                    }
                i++;
            }
            Console.WriteLine(result);
        }

        //recursion :-(
        static int fibonacci(int n)
        {
            if(cache.ContainsKey(n))
            {
                return cache[n];
            }

            int fibNumer = 0;
            if(n == 1 || n == 2)
            {
                return 1;
            } else
            {
                fibNumer = fibonacci(n - 1) + fibonacci(n - 2);
                cache.Add(new KeyValuePair<int, int>(n, fibNumer));
                return fibNumer;
            }
        }
    }
}
